### ISSUE TITLE
Obligatory obvious first feature request: Fully support SDXL

### ISSUE THREAD

**Issue by tildebyte** [ssitu/ComfyUI_restart_sampling#1]

**Comment by ssitu** [comment]
Does an error appear when you try it with SDXL?

**Comment by tildebyte** [comment]
I was going to do that later today :D

**Comment by ssitu** [comment]
I can’t imagine why it wouldn’t work, I don’t think SDXL changed anything about the sampling process.

**Comment by tildebyte** [comment]
Looks good - great, in fact.

If `start_at_step` were exposed, we could use the Restart Sampler with the SDXL Refiner as well.

**Comment by ssitu** [comment]
Glad to hear. I plan on making a node similar to KSampler Advanced after I finish making a node that implements FABRIC.

**Comment by tildebyte** [comment]
I was going to mention the "add_noise" and "return_noise" settings, but it's actually *better* at producing base images for the refiner to consume than the "stock" Comfy sampler, which I can't get to produce "soft" enough images - the refiner *always* ends up overcooking them.

Sample workflow (this is still WIP, so some settings will probably look weird)

![workflow](https://github.com/ssitu/ComfyUI_restart_sampling/assets/337875/fc0b3c67-50e0-4a9c-9816-05ad372bb3d0)

Thanks for the amazing node, and the quick turnaround (the paper was submitted 26 Jun 2023! 😲)

**Comment by tildebyte** [comment]
Closing as already implemented
