### ISSUE TITLE
[Question] segment

### ISSUE THREAD

**Issue by za-wa-n-go** [ssitu/ComfyUI_restart_sampling#2]
Sorry, I am not sure how to enter the proper values for the segments. [4, 1, 19.35, 40.79], [4, 1, 1.09, 1.92], [4, 5, 0.59, 1.09], [4, 5, 0.30, 0.59], [6, 6, 0.06, 0.30] How can I make this happen?

**Comment by ssitu** [comment]
You should be able to just enter `[4, 1, 19.35, 40.79], [4, 1, 1.09, 1.92], [4, 5, 0.59, 1.09], [4, 5, 0.30, 0.59], [6, 6, 0.06, 0.30]` into the `segments` widget.

**Comment by za-wa-n-go** [comment]
[4, 1, 19.35, 40.79], [4, 1, 1.09, 1.92], [4, 5, 0.59, 1.09], [4, 5, 0.30, 0.59], [6, 6, 0.06, 0.30]
What would the behavior be if I wrote more than one of these or if I described the one that I think is appropriate out of these?

**Comment by ssitu** [comment]
I'm not sure if I understand your question. 
Once the denoising process reaches a noise level near 19.34 it will restart at a noise level of 40.79 and denoise back down to the noise level near 19.34 in (4 - 1 = 3) steps. 
Then once it reaches near a noise level of 1.09 it will restart to 1.92 and go back down near 1.09 in 3 steps.
Then ~0.59 -> 1.09, and back down to ~0.59 in (4-1)(5) = 15 steps.
And so on.

**Comment by za-wa-n-go** [comment]
I see. I guess it means to use segments as needed.
In some cases we use [6, 6, 0.06, 0.30], in other cases we use [4, 1, 19.35, 40.79].
Do the recommended SEGMENT values vary from sampler to sampler?

**Comment by ssitu** [comment]
You can choose what those values are, as long as the 3rd value is smaller than the 4th. 
There aren't any recommended segment values, just the ones given in the paper, and they left the deciding of the values in segments for future work, but I'm pretty sure most configurations will give a slight improvement over regular sampling. You'll have to experiment with it.
IMO, segments with high noise like [4, 1, 19.35, 40.79] probably won't do much to improve the result and just gives a different result.
Side note: I think most sd 1.5 models have a max noise of ~14.6, so the segment [4, 1, 19.35, 40.79] will never run because the denoising process starts at 14.6 and won't hit 19.35. I might have to fix that... I also can't run SDXL so I don't know what values of noise they were trained on.

**Comment by za-wa-n-go** [comment]
I'm using it on SDXL... So if it seems to be working, is it working?

**Comment by ssitu** [comment]
What segments have you tried? And have you run into the issue where the progress bar is not being fully completed in the console or in the UI?

**Comment by za-wa-n-go** [comment]
They are trying different things in different orders.
As I recall, I encountered this last night, but have not encountered it in the minutes I am trying today.

**Comment by ssitu** [comment]
The segment order doesn't matter unless one would overwrite another if their t_min's are close together. Anyway, the incomplete progress bar should be fixed now.

**Comment by za-wa-n-go** [comment]
<img width="531" alt="image" src="https://github.com/ssitu/ComfyUI_restart_sampling/assets/118154415/ee52a1a3-de93-41ff-9347-656940b2b54c">
By default, multiple segments are listed, but I wonder if any of them will be given priority in such a case.

**Comment by ssitu** [comment]
If your step count is high enough (maybe more than around 8 steps, which you wouldn't usually do anyway) then you won't run into overwritten segments with those values. If it occurs, a warning will be displayed in the console.

**Comment by za-wa-n-go** [comment]
<img width="311" alt="image" src="https://github.com/ssitu/ComfyUI_restart_sampling/assets/118154415/167dbdd3-326c-43fa-b8d0-d4777e63e940">
<img width="302" alt="image" src="https://github.com/ssitu/ComfyUI_restart_sampling/assets/118154415/bb328ac6-4dcc-4b57-8c95-3519c6f02ffb">
I set it to a higher value as an experiment.
With this value, you stopped in the middle of the process.

**Comment by ssitu** [comment]
I made changes an hour ago, is this on the latest version?

**Comment by za-wa-n-go** [comment]
oh, If it was an hour ago, it is still not up-to-date.

**Comment by za-wa-n-go** [comment]
<img width="224" alt="image" src="https://github.com/ssitu/ComfyUI_restart_sampling/assets/118154415/4d40bdb3-5a79-4627-b0ee-8574846b0b4c">

Since this did not change the picture, SDXL may be the same as SD15 for tmin's ~14.6.
