### ISSUE TITLE
DDIM not working after latest comfyui changes

### ISSUE THREAD

**Issue by luxdeluks** [ssitu/ComfyUI_restart_sampling#3]
Hi, the restart sampler throws an error when trying to run with DDIM

DDIMWrapper.ddim_wrapper() missing 1 required positional argument: 'conditioning'

**Comment by ssitu** [comment]
Thanks for the heads up, should be fixed with now with bfa396b1da0281d05f69bfdc3cf4a2d41dfa46ef
