### ISSUE TITLE
Subject: Error Report - Lack of Support for Older Python Versions

### ISSUE THREAD

**Issue by shiertier** [ssitu/ComfyUI_restart_sampling#4]
Dear developer,

I have encountered an issue while using your code, which seems to be caused by compatibility problems with older versions of Python. Below are the specific error details and the problematic code segment:

```
def restart_sampling(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, restart_info, restart_scheduler, denoise=1.0, disable_noise=False, start_step=None, last_step=None, force_full_denoise=False):
    global _total_steps, _restart_segments, _restart_scheduler
    _restart_scheduler = restart_scheduler
    _restart_segments = prepare_restart_segments(restart_info)

    match sampler_name:
        case "ddim":
            sampler_wrapper = DDIMWrapper()
        case _:
            sampler_wrapper = KSamplerRestartWrapper(sampler_name)

    match sampler_name:
          ^
SyntaxError: invalid syntax
```

The above error occurs due to the usage of pattern matching syntax introduced in Python 3.10, which is not compatible with older Python versions.

To make your code accessible to a wider range of users, I recommend considering compatibility with older Python versions. Here is an alternative code snippet that replaces pattern matching with if/else statements:

```
if sampler_name == "ddim":
    sampler_wrapper = DDIMWrapper()
else:
    sampler_wrapper = KSamplerRestartWrapper(sampler_name)
```

By adopting this approach, you can ensure that your code runs smoothly on older Python versions.

**Comment by shiertier** [comment]
And again, line 129

```
if sampler == "ddim":
    sampler = DDIMSampler(self.model, device=self.device)
    sampler.make_schedule_timesteps(ddim_timesteps=timesteps, verbose=False)
    z_enc = sampler.stochastic_encode(latent_image, torch.tensor(
        [len(timesteps) - 1] * noise.shape[0]).to(self.device), noise=noise, max_denoise=max_denoise)
    samples, _ = sampler.sample_custom(ddim_timesteps=timesteps,
                                       conditioning=positive,
                                       batch_size=noise.shape[0],
                                       shape=noise.shape[1:],
                                       verbose=False,
                                       unconditional_guidance_scale=cfg,
                                       unconditional_conditioning=negative,
                                       eta=0.0,
                                       x_T=z_enc,
                                       x0=latent_image,
                                       img_callback=ddim_callback,
                                       denoise_function=sampling_function,
                                       extra_args=extra_args,
                                       mask=noise_mask,
                                       to_zero=sigmas[-1] == 0,
                                       end_step=sigmas.shape[0] - 1,
                                       disable_pbar=disable_pbar)
else:
    sample = getattr(k_diffusion_sampling, f"sample_{sampler}")
```

**Comment by shiertier** [comment]
> 第 129 行
> 
> ```
> if sampler == "ddim":
>     sampler = DDIMSampler(self.model, device=self.device)
>     sampler.make_schedule_timesteps(ddim_timesteps=timesteps, verbose=False)
>     z_enc = sampler.stochastic_encode(latent_image, torch.tensor(
>         [len(timesteps) - 1] * noise.shape[0]).to(self.device), noise=noise, max_denoise=max_denoise)
>     samples, _ = sampler.sample_custom(ddim_timesteps=timesteps,
>                                        conditioning=positive,
>                                        batch_size=noise.shape[0],
>                                        shape=noise.shape[1:],
>                                        verbose=False,
>                                        unconditional_guidance_scale=cfg,
>                                        unconditional_conditioning=negative,
>                                        eta=0.0,
>                                        x_T=z_enc,
>                                        x0=latent_image,
>                                        img_callback=ddim_callback,
>                                        denoise_function=sampling_function,
>                                        extra_args=extra_args,
>                                        mask=noise_mask,
>                                        to_zero=sigmas[-1] == 0,
>                                        end_step=sigmas.shape[0] - 1,
>                                        disable_pbar=disable_pbar)
> else:
>     sample = getattr(k_diffusion_sampling, f"sample_{sampler}")
> ```

**Comment by shiertier** [comment]
Line 129
```
if sampler == "ddim":
    sampler = DDIMSampler(self.model, device=self.device)
    sampler.make_schedule_timesteps(ddim_timesteps=timesteps, verbose=False)
    z_enc = sampler.stochastic_encode(latent_image, torch.tensor(
        [len(timesteps) - 1] * noise.shape[0]).to(self.device), noise=noise, max_denoise=max_denoise)
    samples, _ = sampler.sample_custom(ddim_timesteps=timesteps,
                                       conditioning=positive,
                                       batch_size=noise.shape[0],
                                       shape=noise.shape[1:],
                                       verbose=False,
                                       unconditional_guidance_scale=cfg,
                                       unconditional_conditioning=negative,
Eta = 0.0,
                                       x_T=z_enc,
                                       x0=latent_image,
                                       img_callback=ddim_callback,
                                       denoise_function=sampling_function,
                                       extra_args=extra_args,
                                       mask=noise_mask,
                                       to_zero=sigmas[-1] == 0,
                                       end_step=sigmas.shape[0] - 1,
                                       disable_pbar=disable_pbar)
else:
    sample = getattr(k_diffusion_sampling, f"sample_{sampler}")
```

**Comment by ssitu** [comment]
Good catch, made the changes here: 704196b0701982b295073cec1a5f3a47d568cfec
